// Writes dist/_headers after every build.
//
// The Content-Security-Policy here is not just hardening — it is the privacy
// page's promise expressed in a form a browser enforces. `connect-src` limits
// the site to its own origin and the analytics beacon, so a script that tried to
// POST a roster somewhere would be blocked by the browser, not merely by our
// good intentions. That is a claim worth being able to make literally.
//
// Hashes are computed from the built HTML rather than hand-pinned: 19 pages emit
// 39 distinct inline scripts (the theme bootstrap, the island loaders, and a
// different JSON-LD block per page), so any hand-maintained list would be wrong
// within a week. tests/smoke-csp.mjs then serves dist under these exact headers
// and fails on any violation, because `astro preview` ignores _headers and a
// broken CSP is otherwise invisible until it is live.
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const BEACON_SCRIPT = 'https://static.cloudflareinsights.com';
const BEACON_CONNECT = 'https://cloudflareinsights.com';

// Google Analytics 4. Listed unconditionally rather than only when PUBLIC_GA_ID
// is set, so the policy a local build and tests/smoke-csp.mjs exercise is byte
// for byte the policy production serves — a CSP that differs between the build
// you test and the build you ship is not a CSP you have tested.
//
// Allowing the origin is not the same as contacting it: gtag.js is injected
// only after the teacher accepts analytics (see the consent gate in
// Layout.astro). Until then nothing here is ever requested.
const GA_SCRIPT = 'https://www.googletagmanager.com';
const GA_CONNECT = 'https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com';
// GA still falls back to an image ping on browsers that block fetch/beacon.
const GA_IMG = 'https://www.google-analytics.com';

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    if (e.isDirectory()) return htmlFiles(p);
    return e.name.endsWith('.html') ? [p] : [];
  });
}

const sha256 = (s) => `'sha256-${createHash('sha256').update(s, 'utf8').digest('base64')}'`;

/**
 * Inline <script>/<style> bodies in a page; elements with src/href are skipped,
 * and so are JSON-LD data blocks.
 *
 * script-src governs script *execution*. A <script type="application/ld+json">
 * is a data block the browser parses and never runs, so there is nothing for the
 * policy to allow — no engine reports a violation for one. Hashing them anyway
 * was not merely wasteful: 37 of the 46 script hashes came from JSON-LD, and
 * they pushed the Content-Security-Policy line to 4,022 characters. Both Pages
 * and Workers cap a _headers line at 2,000, so the entire policy would have been
 * dropped on deploy — the privacy claim silently unenforced. See the length
 * guard below, which is what should have caught it.
 */
function inlineBodies(html, tag) {
  const out = [];
  for (const m of html.matchAll(new RegExp(`<${tag}([^>]*)>([\\s\\S]*?)</${tag}>`, 'g'))) {
    if (/\s(src|href)=/.test(m[1])) continue;
    if (tag === 'script' && /type=["']application\/ld\+json["']/.test(m[1])) continue;
    out.push(m[2]);
  }
  return out;
}

/** Cloudflare parses _headers line by line and caps each at 2,000 characters. */
const MAX_HEADER_LINE = 2000;

export function cspHeaders() {
  return {
    name: 'rosterowl:csp-headers',
    hooks: {
      'astro:build:done': ({ dir, logger }) => {
        const root = dir.pathname;
        const scripts = new Set();
        const styles = new Set();

        for (const file of htmlFiles(root)) {
          const html = readFileSync(file, 'utf8');
          for (const body of inlineBodies(html, 'script')) scripts.add(sha256(body));
          for (const body of inlineBodies(html, 'style')) styles.add(sha256(body));
        }

        const csp = [
          `default-src 'self'`,
          `base-uri 'none'`,
          `form-action 'none'`,
          `frame-ancestors 'none'`,
          `script-src 'self' ${BEACON_SCRIPT} ${GA_SCRIPT} ${[...scripts].join(' ')}`,
          `style-src 'self' ${[...styles].join(' ')}`,
          // Svelte transitions animate via the element's style attribute.
          `style-src-attr 'unsafe-inline'`,
          `font-src 'self'`,
          // blob: is the generated PDF and its PNG render; data: is canvas output.
          `img-src 'self' data: blob: ${GA_IMG}`,
          `object-src 'self' blob:`,
          // The PDF preview embeds a blob: URL; some engines treat it as a frame.
          `frame-src 'self' blob:`,
          // The pdf.js render worker and the service worker.
          `worker-src 'self' blob:`,
          `connect-src 'self' ${BEACON_CONNECT} ${GA_CONNECT}`,
          `manifest-src 'self'`,
        ].join('; ');

        const headers = `# Generated by tools/csp/integration.mjs on every build — do not edit.
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), camera=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin

# Content-addressed by the build — safe to keep forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable

# Icons and cards change without changing name, so revalidate daily.
/og/*
  Cache-Control: public, max-age=86400
/*.png
  Cache-Control: public, max-age=86400
/favicon.ico
  Cache-Control: public, max-age=86400

# The service worker must never be served stale, or updates never land.
/sw.js
  Cache-Control: no-cache
`;

        // Fail the build rather than ship a policy the platform will discard.
        // A truncated CSP is invisible: the site works, and nothing is enforced.
        const tooLong = headers
          .split('\n')
          .map((line, i) => ({ n: i + 1, len: line.length, line }))
          .filter((l) => l.len > MAX_HEADER_LINE);
        if (tooLong.length > 0) {
          const detail = tooLong
            .map((l) => `  line ${l.n}: ${l.len} chars — ${l.line.trim().slice(0, 48)}…`)
            .join('\n');
          throw new Error(
            `_headers has ${tooLong.length} line(s) over Cloudflare's ${MAX_HEADER_LINE}-character ` +
              `limit, which would be dropped on deploy:\n${detail}\n` +
              'Reduce the number of inline scripts or styles the build emits.',
          );
        }

        writeFileSync(join(root, '_headers'), headers);
        logger.info(`_headers written (${scripts.size} script + ${styles.size} style hashes)`);

        if (!process.env.PUBLIC_CF_BEACON_TOKEN) {
          logger.warn(
            'PUBLIC_CF_BEACON_TOKEN is unset — this build has no analytics. Production builds ' +
              'need it, or /privacy/ overstates what the site does.',
          );
        }
      },
    },
  };
}
