// Writes dist/_redirects after every build.
//
// Astro builds directory-style routes (dist/terms/index.html), so the canonical
// URL of every page carries a trailing slash — that is what the sitemap lists,
// what <link rel="canonical"> points at, and what every internal link uses.
//
// Cloudflare's asset router already sends /terms to /terms/, but it does so
// with a 307, and that status is not configurable. A 307 is a *temporary*
// redirect: it tells a search engine not to consolidate ranking signals onto
// the target. For a site whose entire growth plan is organic search, and whose
// inbound links from teachers and blogs will routinely omit the trailing slash,
// that is a quiet tax on every one of those links.
//
// So one explicit 301 per real route, generated from the pages the build
// actually emitted rather than a hand-kept list that would drift the first time
// a page was added.
import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

/** Cloudflare accepts at most 2,000 static redirect rules. */
const MAX_RULES = 2000;

/** Every directory-style route in the build, as "terms", "seating-chart/u-shape", … */
function routes(root) {
  const found = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name === 'index.html') {
        const route = relative(root, dir).split('\\').join('/');
        // The root is already "/" and has no slashless form to redirect.
        if (route) found.push(route);
      }
    }
  };
  walk(root);
  return found.sort();
}

export function redirects() {
  return {
    name: 'rosterowl:redirects',
    hooks: {
      'astro:build:done': ({ dir, logger }) => {
        const root = dir.pathname;
        const list = routes(root);

        if (list.length > MAX_RULES) {
          throw new Error(
            `_redirects would need ${list.length} rules, over Cloudflare's ${MAX_RULES} limit. ` +
              'Switch to a wildcard rule or a zone-level redirect rule instead.'
          );
        }

        const body = [
          '# Generated by tools/redirects/integration.mjs on every build — do not edit.',
          '#',
          '# Canonical URLs carry a trailing slash. Cloudflare would redirect these',
          '# anyway, but only with a 307; these make it a permanent 301 so inbound',
          '# links without the slash pass their full weight to the canonical URL.',
          ...list.map((route) => `/${route} /${route}/ 301`),
          '',
        ].join('\n');

        writeFileSync(join(root, '_redirects'), body);
        logger.info(`_redirects written (${list.length} canonical 301s)`);
      },
    },
  };
}
